name: Bug report
description: Report a bug
labels: [bug]
body:
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Explain what you expected and what actually happened.
    validations:
      required: true
